### ISSUE TITLE
Spurious CI failures on macOS with GCC 9

### ISSUE THREAD

**Issue by AeroStun** [DIT112-V20/group-09#30]
The default `libstdc++` does not provide `std::chrono` symbols to our PIC static library

**Comment by RuthgerD** [comment]
Fixed with #28

**Comment by AeroStun** [comment]
#28 Did not fix the underlying issue; it simply avoided it; reopening so it can be used to document that behavior and hopefully later be fixed
